// Generated by CoffeeScript 1.6.3
var canvas, download, drawScene, generateShader, gl, greyscale, handleLoadedTexture, initBuffers, initShaders, initTexture, mode, onFileSelect, setGreyscale, setMode, setSlider, shaderProgram, slider, texture, textureBuffer, vertexBuffer, webGlStart;

canvas = null;

gl = null;

shaderProgram = null;

vertexBuffer = null;

textureBuffer = null;

texture = null;

mode = "raw";

greyscale = true;

slider = 1.0;

initShaders = function(shaderNames) {
  shaderProgram = createProgramFromScripts(gl, shaderNames);
  gl.useProgram(shaderProgram);
  shaderProgram.vertexPositionAttribute = gl.getAttribLocation(shaderProgram, "aVertexPosition");
  gl.enableVertexAttribArray(shaderProgram.vertexPositionAttribute);
  shaderProgram.textureCoordAttribute = gl.getAttribLocation(shaderProgram, "aTextureCoord");
  return gl.enableVertexAttribArray(shaderProgram.textureCoordAttribute);
};

initBuffers = function() {
  var textureCoords, vertices;
  vertexBuffer = gl.createBuffer();
  gl.bindBuffer(gl.ARRAY_BUFFER, vertexBuffer);
  vertices = [-1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, 1.0];
  gl.bufferData(gl.ARRAY_BUFFER, new Float32Array(vertices), gl.STATIC_DRAW);
  vertexBuffer.itemSize = 2;
  textureBuffer = gl.createBuffer();
  gl.bindBuffer(gl.ARRAY_BUFFER, textureBuffer);
  textureCoords = [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0];
  gl.bufferData(gl.ARRAY_BUFFER, new Float32Array(textureCoords), gl.STATIC_DRAW);
  return textureBuffer.itemSize = 2;
};

handleLoadedTexture = function(texture) {
  gl.bindTexture(gl.TEXTURE_2D, texture);
  gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true);
  gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, texture.image);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
  gl.bindTexture(gl.TEXTURE_2D, null);
  return drawScene(false);
};

initTexture = function(fileObject) {
  texture = gl.createTexture();
  if (!texture) {
    alert("Failed to create square buffer");
  }
  if (texture) {
    texture.image = new Image();
    if (!texture.image) {
      alert("Failed to create image");
    }
  }
  if (texture && texture.image) {
    texture.image.onload = function() {
      return handleLoadedTexture(texture);
    };
    return texture.image.src = fileObject;
  }
};

drawScene = function(returnImage) {
  var pGreyscaleUniform, pModeUniform, pSliderUniform;
  gl.bindBuffer(gl.ARRAY_BUFFER, vertexBuffer);
  gl.vertexAttribPointer(shaderProgram.vertexPositionAttribute, vertexBuffer.itemSize, gl.FLOAT, false, 0, 0);
  gl.bindBuffer(gl.ARRAY_BUFFER, textureBuffer);
  gl.vertexAttribPointer(shaderProgram.textureCoordAttribute, textureBuffer.itemSize, gl.FLOAT, false, 0, 0);
  if (mode === "infragrammar") {
    pSliderUniform = gl.getUniformLocation(shaderProgram, "uSlider");
    gl.uniform1f(pSliderUniform, slider);
  } else {
    pModeUniform = gl.getUniformLocation(shaderProgram, "uMode");
    switch (mode) {
      case "ndvi":
        gl.uniform1f(pModeUniform, 1.0);
        break;
      case "nir":
        gl.uniform1f(pModeUniform, 2.0);
        break;
      default:
        gl.uniform1f(pModeUniform, 0.0);
    }
    pGreyscaleUniform = gl.getUniformLocation(shaderProgram, "uGreyscale");
    if (greyscale) {
      gl.uniform1f(pGreyscaleUniform, 1.0);
    } else {
      gl.uniform1f(pGreyscaleUniform, 0.0);
    }
  }
  gl.activeTexture(gl.TEXTURE0);
  gl.bindTexture(gl.TEXTURE_2D, texture);
  gl.drawArrays(gl.TRIANGLES, 0, 6);
  if (returnImage) {
    return canvas.toDataURL("image/png");
  }
};

generateShader = function(r, g, b) {
  r = r.toLowerCase().replace(/[^srgb\/\-\+\*\(\)\.0-9]*/g, "");
  g = g.toLowerCase().replace(/[^srgb\/\-\+\*\(\)\.0-9]*/g, "");
  b = b.toLowerCase().replace(/[^srgb\/\-\+\*\(\)\.0-9]*/g, "");
  r = r.replace(/([0-9])([^\.])?/g, "$1.0$2");
  g = g.replace(/([0-9])([^\.])?/g, "$1.0$2");
  b = b.replace(/([0-9])([^\.])?/g, "$1.0$2");
  return document.getElementById("generated-shader-fs").text = "        precision mediump float;        varying vec2 vTextureCoord;        uniform sampler2D uSampler;        uniform float uSlider;        void main(void)        {            vec4 color = texture2D(uSampler, vTextureCoord);            float s = uSlider;            float r = color.r;            float g = color.g;            float b = color.b;" + "float rr = " + r + ";" + "float gg = " + g + ";" + "float bb = " + b + ";" + "gl_FragColor = vec4(rr, gg, bb, 1.0);        }";
};

webGlStart = function() {
  canvas = document.getElementById("canvas-image");
  gl = getWebGLContext(canvas);
  return initBuffers();
};

download = function() {
  var event, lnk;
  lnk = document.createElement("a");
  lnk.download = (new Date()).toISOString().replace(":", "_") + ".png";
  lnk.href = drawScene(true);
  if (document.createEvent) {
    event = document.createEvent("MouseEvents");
    event.initMouseEvent("click", true, true, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);
    return lnk.dispatchEvent(event);
  } else if (lnk.fireEvent) {
    return lnk.fireEvent("onclick");
  }
};

setGreyscale = function(value) {
  greyscale = value;
  drawScene(false);
  return $("#download").show();
};

setSlider = function(value) {
  slider = value;
  return drawScene(false);
};

setMode = function(newMode) {
  mode = newMode;
  if (mode === "infragrammar") {
    initShaders(["shader-vs", "generated-shader-fs"]);
  } else {
    initShaders(["shader-vs", "shader-fs"]);
  }
  drawScene(false);
  $("#download").show();
  if (mode === "ndvi") {
    return $("#colormaps-group")[0].style.display = "inline-block";
  } else {
    return $("#colormaps-group")[0].style.display = "none";
  }
};

onFileSelect = function() {
  var input, reader;
  input = document.getElementById("file-sel");
  if (input.files && input.files[0]) {
    reader = new FileReader();
    reader.onload = function(e) {
      initShaders(["shader-vs", "shader-fs"]);
      initTexture(e.target.result);
      return $("#download").show();
    };
    return reader.readAsDataURL(input.files[0]);
  }
};
